version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    # volumes:
    #   - mongo-data:/data/db
    ports:
      - "27017:27017"
# volumes:
#   mongo-data: